name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build v10
      run: cargo build --example synth_directly_v10 --verbose
    - name: Build v11
      run: cargo build --example synth_directly_v11 --verbose
    - name: Run tests
      run: cargo test --verbose
